POST http://localhost:7070/api/hotel
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwOTc2NTksInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.x2JcD4vLiykju8Ith4uedGEW7nIcRLJDrL95vdipQQw

{
"name":"test",
"address":"Coolroad"
}
###

PUT http://localhost:7070/api/hotel/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwNjc2OTEsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.oIjY4b4YZ-Re0u3vnxy_h1IYz_EL8VljJyODTOXZddE

{
"name":"updatedName",
"address":"updatedRoad"
}
###

DELETE http://localhost:7070/api/hotel/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwNjc2OTEsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.oIjY4b4YZ-Re0u3vnxy_h1IYz_EL8VljJyODTOXZddE

###

POST http://localhost:7070/api/room
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwNjc2OTEsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.oIjY4b4YZ-Re0u3vnxy_h1IYz_EL8VljJyODTOXZddE

{
"hotelId":15,
"number":99,
"price":900000

}
###

PUT http://localhost:7070/api/room/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwNjc2OTEsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.oIjY4b4YZ-Re0u3vnxy_h1IYz_EL8VljJyODTOXZddE

{
"hotelId":3,
"number":1234,
"price":333
}
###

DELETE http://localhost:7070/api/room/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwNjc2OTEsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.oIjY4b4YZ-Re0u3vnxy_h1IYz_EL8VljJyODTOXZddE

###

POST http://localhost:7070/api/auth/register

{

"username":"Coolgutmand",
"password":"coolkode21"

}
###

POST http://localhost:7070/api/auth/login

{
"username":"Coolgutmand",
"password":"coolkode21"
}

###

POST http://localhost:7070/api/auth/login

{
"username":"Admin",
"password":"Bigpassword"
}

###


GET http://localhost:7070/api/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwOTc2NTksInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.x2JcD4vLiykju8Ith4uedGEW7nIcRLJDrL95vdipQQw
###

GET http://localhost:7070/api/protected/admin_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJOaWNrbGFzIFcuIiwic3ViIjoiQWRtaW4iLCJleHAiOjE3MTEwOTc2NTksInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6IkFkbWluIn0.x2JcD4vLiykju8Ith4uedGEW7nIcRLJDrL95vdipQQw
###